language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - rbx
gemfile:
  - gemfiles/Gemfile.paperclip-2.x
  - gemfiles/Gemfile.paperclip-3.x
  - gemfiles/Gemfile.paperclip-4.x
allow_failures:
  - rvm: jruby-19mode
  - rvm: rbx
