language: ruby
rvm:
  - 1.9.3
  - 2.1
  - jruby-19mode
  - rbx
gemfile:
  - gemfiles/Gemfile.paperclip-2.x
  - gemfiles/Gemfile.paperclip-3.x
  - gemfiles/Gemfile.paperclip-4.x
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx
